name: 葱花刷视频

on:
  workflow_dispatch:
  # 账号越多文章越多，运行一次消耗的时间也越长，文章和视频不要一块运行，cron自己看着写
  schedule:
     - cron: '10 0,1,2,3,4,5,6,7,8,9,10 * * *'
  watch:
    types: started
jobs:
  build:
    env:
      RONGHUA_VIDEO: ${{ secrets.RONGHUA_VIDEO }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【葱花视频-自动刷视频】'
        if: env.RONGHUA_VIDEO
        run: |
          node RONGHUA_VIDEO.js
        env:
          RONGHUA_READ: ${{ secrets.RONGHUA_VIDEO }}
