name: 返利网

on:
    workflow_dispatch:
    schedule:
        - cron: "5 0-2 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【返利网】"
              run: |
                  node flw.js
                  
              env:
                  FL_FLWURL: ${{ secrets.FL_FLWURL }}
                  FL_FLWHEADER: ${{ secrets.FL_FLWHEADER }}
                  FL_FLWSPBODY: ${{ secrets.FL_FLWSPBODY }}
                  FL_FLWQWBODY: ${{ secrets.FL_FLWQWBODY }}
                  FL_CASH: ${{ secrets.FL_CASH }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
                  
